# Job config


# Database
db.path=data/jobs.db
db.in.memory=false

# Scheduling
scheduling.logs.dir=data/logs
scheduling.pool.size=4
scheduling.poll.interval.ms=6000
scheduling.max.concurrent.processes=100
scheduler.jobs=demo/loads_of_jobs.yaml

# Vault
vault.address=http://127.0.0.1:8200
vault.secret.path=secret/my-scheduler

# Monitoring
monitoring.interval.seconds=30
